
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.91.0:3306/first?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: "1234"

    thymeleaf:
      prefix: classpath:/templates/
      cache: false
      check-template-location: true
      suffix: .html